import api from './index'
export const getRoles = (params) => api.get('/roles', { params })
export const getRolesForAssignment = () => api.get('/roles', { params: { for_assignment: true } })
export const getRole = (id) => api.get(`/roles/${id}`)
export const createRole = (data) => api.post('/roles', data)
export const updateRole = (id, data) => api.put(`/roles/${id}`, data)
export const deleteRole = (id) => api.delete(`/roles/${id}`)
export const assignPermissions = (id, data) => api.put(`/roles/${id}/permissions`, data)
export const getPermissions = () => api.get('/permissions')
export const getPermissionsGrouped = () => api.get('/permissions/grouped')
